### PR TITLE
Superagent and client side

### PR DESCRIPTION
**Pull request by iendjinn**
Replaced request with superagent. 

Includes a client side version of the tdx  code, include client-api.js in html file and the global construction TDXApi is added. 

To regenerate client-api.js:
browserify client-index.js -o client-api.js

### CODE REVIEW

**Comment by TobyEalden** [comment]
Can you format the chained method calls on separate lines, e.g.

```
request.post(command)
  .set(header)
  .send(postData)
  .end (function(err, response) {
    args.cb(err, body);
    if (handleResponse("register process host", err, response, args.cb)) {
      args.cb(err, response.body);
    }
  });
```

**Comment by TobyEalden** [comment]
Much better - thanks.

Is client_index.js needed? I think

```
<script src="client-api.js" />
```

will do?

**Comment by iendjinn** [comment]
client-index.js needed to rebuild client-api.js

i.e. browserify client-index.js -o client-api.js

**Comment by TobyEalden** [comment]
OK got it. I'll merge this now, issue a separate PR for the build stuff.

**Pull request merged**
