### PR TITLE
Auto generate browserify

### PR DESCRIPTION
**Pull request by iendjinn**

### CODE REVIEW

**Comment by TobyEalden** [comment]
does browsify need to be a package dependency? Or is it a global install only?

**Comment by iendjinn** [comment]
Must be installed with the package to ensure the browserify works on npm
install I think.

**Comment by TobyEalden** [comment]
So shouldn't browserify be in package.json?

**Comment by iendjinn** [comment]
Forgot to add to package.json, also added superagent...

**Comment by TobyEalden** [comment]
Is it worth adding a browser field - https://github.com/substack/browserify-handbook#browser-field

**Comment by iendjinn** [comment]
I thought the whole point of browserify was that browser javascript didn't
support require? I.e. you have to generate a browserified file and then
include it in a script tag for it to handle the "require()" function.

**Comment by TobyEalden** [comment]
I guess it's to support AMD and commonjs which a lot of people are using. Not sure if it will also give hints for ES6 module syntax. Probably not a big deal for us right now.

**Comment by TobyEalden** [comment]
https://github.com/nqminds/nqm-api-tdx/pull/4

**Pull request closed without merging**
