### PR TITLE
URL escape aggregate pipeline

### PR DESCRIPTION
**Pull request by iendjinn**
This fixes a bug whereby characters included in a pipeline which are not URL safe (such as &) would cause a JSON parsing error to be thrown. I'm not sure if this will need a matching decode in the query handler as pipeline somehow becomes a param as oppose to a query item which express automatically decodes (https://github.com/nqminds/nqm-tdx/blob/master/packages/nqm-core-query/lib/http-query-listener.js#L439)

### CODE REVIEW

**Comment by iendjinn** [comment]
I have confirmed that this fix works testing locally @TobyEalden

**Comment by TobyEalden** [comment]
OK thanks - I'm planning a release in the next week or two with some updates to accomodate the new core so I'll check it out then.

In the meantime you can encode it from the client if it's causing you problems.

Also, I think [this check](https://github.com/nqminds/nqm-api-tdx/blob/a6d6673887478a83ce7702458f9016fcd49aecd5/src/api-tdx.js#L1433) might need to be taken into account, otherwise any existing code that uses an already encoded pipeline might break.

**Comment by iendjinn** [comment]
I've updated the code to decode the input text first and tested it in the following scenarios and confirmed it produces the expected result:

- pipeline is a regular json object
- pipeline is a stringified json object
- pipeline is a json object containing url encoded values
- pipeline is a stringified json object that has then been url encoded

**Comment by iendjinn** [comment]
Added in 938bbcaad1417312e4108aef0d15014e25226a60

**Pull request closed without merging**
